config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#index'
  resource :session, only: [:create, :new, :destroy]
  resource :users, only:[:new, :create]

 namespace :api, :defaults => { :format => :json } do
 		resources :feeds, only: [:index] do 
      collection do
        get 'recent', to: 'feeds#recent'
      end
    end

		resources :users, only: [:show, :update, :destroy] do 
			resource :follow, only: [:create, :destroy]
		end

		resources :photos, only: [:index, :create, :show, :destroy]
    resources :likes, only: [:create]
    delete 'likes', to: "likes#destroy"
		resources :comments, only: [:create, :index, :update, :destroy]
  end

end

app/views/layouts/_errors.html.erb
<% if flash[:errors] %>
<div class="alert alert-warning alert-dismissible" role="alert">
   <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
<%= flash[:errors].join("<br>").html_safe %>
</div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="navigation">
  <div class="pull-left">
    <div class="home-icon">
      <a class='home-button' href="#">
        <i class="fa fa-home fa-lg"></i>
      </a>
    </div>
    <div class="new-icon">
      <a class='home-button' href="#new">
        <i class="fa fa-camera"></i>
      </a>
    </div>
    <div class="explore-icon">
      <a class='explore-btn' href="#explore">
       <i class="fa fa-users fa-lg"></i>
      </a>
    </div>
  </div>

  <div class="center-group">
    <div class="nav-heading">
      <a class='logo-link' href='#'><img class='header-logo' src='https://s3.amazonaws.com/kittenstagramdev/images/photos/Final+Logo+(Light+Color).png'><img class="center-logo" src='https://s3-us-west-1.amazonaws.com/kitdevaws/images/photos/header.png'></a>
    </div>
  </div>

  <div class='pull-right'>
  <ul>
  <% if signed_in? %>
    <div class="navbar-profile-pane"></div>
    <li><%= button_to "Sign out", session_url, method: :delete, class: "navbar-btn custom-button sign-out-btn" %></li>
  <% else %>
    <li class="sign-in-text"><%= link_to "Log in", new_session_url %></li>
    <li class="sign-in-text"><%= link_to "Sign up", new_users_url %></li>
  <% end %>
  </ul>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kittenstagram</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width,user-scalable=no">
	<link href='//fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps:700' rel='stylesheet' type='text/css'>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
  <%= render partial: "layouts/header" %>
<body>
	<%= yield %>


</body>

<script>
<% if current_user %>
CURRENT_USER_ID = <%= current_user.id %>
<% end %>
</script>
</html>